<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Multivariate-Linear-Regression" data-toc-modified-id="Multivariate-Linear-Regression-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Multivariate Linear Regression</a></span><ul class="toc-item"><li><span><a href="#Preparation" data-toc-modified-id="Preparation-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Preparation</a></span><ul class="toc-item"><li><span><a href="#Importing-relevant-packages" data-toc-modified-id="Importing-relevant-packages-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>Importing relevant packages</a></span></li><li><span><a href="#Defining-Variables" data-toc-modified-id="Defining-Variables-1.1.2"><span class="toc-item-num">1.1.2&nbsp;&nbsp;</span>Defining Variables</a></span></li><li><span><a href="#Define-the-initial-w-and-b" data-toc-modified-id="Define-the-initial-w-and-b-1.1.3"><span class="toc-item-num">1.1.3&nbsp;&nbsp;</span>Define the initial w and b</a></span></li></ul></li><li><span><a href="#Set-up-the-model" data-toc-modified-id="Set-up-the-model-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Set up the model</a></span><ul class="toc-item"><li><span><a href="#Set-up-the-cost-function" data-toc-modified-id="Set-up-the-cost-function-1.2.1"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>Set up the cost function</a></span></li><li><span><a href="#Set-up-the-Gradient-Descent" data-toc-modified-id="Set-up-the-Gradient-Descent-1.2.2"><span class="toc-item-num">1.2.2&nbsp;&nbsp;</span>Set up the Gradient Descent</a></span></li><li><span><a href="#Test-the-Implement" data-toc-modified-id="Test-the-Implement-1.2.3"><span class="toc-item-num">1.2.3&nbsp;&nbsp;</span>Test the Implement</a></span></li></ul></li><li><span><a href="#Do-the-prediction" data-toc-modified-id="Do-the-prediction-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Do the prediction</a></span></li><li><span><a href="#Regularization" data-toc-modified-id="Regularization-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Regularization</a></span></li></ul></li></ul></div>

# Multivariate Linear Regression

## Preparation

### Importing relevant packages

In [21]:
import copy, math
import numpy as np
import matplotlib.pyplot as plt

### Defining Variables

In [22]:
x_train = np.array(np.random.uniform(1,10,(2,3))) #Modify this. (2,3) means 2 training sets and 3 features
y_train = np.array(np.random.uniform(1,10,2)) #Modify this.

In [23]:
print(f"X Shape: {x_train.shape}, X Type:{type(x_train)})")
print(x_train)
print(f"y Shape: {y_train.shape}, y Type:{type(y_train)})")
print(y_train)

X Shape: (2, 3), X Type:<class 'numpy.ndarray'>)
[[7.48740508 2.71735649 8.23433695]
 [1.16792687 3.72502867 6.03337478]]
y Shape: (2,), y Type:<class 'numpy.ndarray'>)
[2.19589131 5.25420704]


### Define the initial w and b

In [24]:
w_init = np.array([1,1,1]) #Modify this. 
b_init = 0

## Set up the model

In [25]:
def predict(x,w,b):
    p = np.dot(x, w) + b
    return p

In [26]:
f_wb = predict(x_train,w_init,b_init)

print(f"The initial predict is {f_wb}.")

The initial predict is [18.43909851 10.92633032].


### Set up the cost function

In [27]:
def compute_cost(x,y,w,b):
    m = x.shape[0]
    cost = 0.0
    for i in range(m):
        f_wb_i = predict(x[i],w,b)
        cost = cost + (f_wb_i - y[i])**2
    cost = cost / (2*m)
    return cost

In [28]:
cost = compute_cost(x_train, y_train, w_init, b_init)
print(f'Cost at initial w : {cost}')

Cost at initial w : 74.00369069724296


### Set up the Gradient Descent

In [29]:
def compute_gradient(x,y,w,b): 
    m,n = x.shape
    dj_dw = np.zeros((n,))
    dj_db = 0.0
    
    for i in range(m):
        error = predict(x[i],w,b)-y[i]
        dj_db = dj_db + error
        for j in range(n):
            dj_dw[j] = dj_dw[j] + error * x[i,j]
    dj_db = dj_db / m
    dj_dw = dj_dw / m
    
    return dj_dw, dj_db

In [30]:
tmp_dj_dw, tmp_dj_db = compute_gradient(x_train, y_train, w_init, b_init)
print(f'dj_dw at initial w,b: \n {tmp_dj_dw}')
print(f'dj_db at initial w,b: {tmp_dj_db}')

dj_dw at initial w,b: 
 [64.12204869 32.63370314 83.98704337]
dj_db at initial w,b: 10.957665241691023


In [31]:
def gradient_descent(x,y,w_int,b_int,cost_func,gradient_func,alpha,iteration): 
    w = copy.deepcopy(w_int)
    b = b_int
    J = cost_func(x,y,w_int,b_int)
    for i in range(iteration):
        dj_dw,dj_db = gradient_func(x,y,w,b)
        w = w - alpha * dj_dw
        b = b - alpha * dj_db
        J = cost_func(x,y,w,b)
        if i% math.ceil(iteration / 10) == 0:
            print(f"Iteration {i:4d}: Cost {J}")
    return w,b,J

### Test the Implement

In [32]:
alpha = 5e-6 #Modify this.
iteration = 10000 #Modify this.

w_final, b_final,J = gradient_descent(x_train, y_train, w_init, b_init,
                                                    compute_cost, compute_gradient, 
                                                    alpha, iteration)
print(f"b,w found by gradient descent: {b_final:0.2f},{w_final} ")

Iteration    0: Cost 73.94195153831879
Iteration 1000: Cost 32.5548650383712
Iteration 2000: Cost 15.013939574834748
Iteration 3000: Cost 7.537650975949608
Iteration 4000: Cost 4.311811782278135
Iteration 5000: Cost 2.8833662889408735
Iteration 6000: Cost 2.217207919875875
Iteration 7000: Cost 1.8764238719627304
Iteration 8000: Cost 1.6764707888163632
Iteration 9000: Cost 1.5392838532319897
b,w found by gradient descent: -0.11,[0.12619805 0.72209441 0.09544635] 


## Do the prediction

In [33]:
x_value = np.array(np.random.uniform(10,20,(1,3))) #Modify this.
y_predict = predict(x_value,w_final,b_final)
print(f"Predicted value for x = {x_value} is {y_predict}")

Predicted value for x = [[14.29134834 14.63448274 15.01191477]] is [13.69717511]
