# Hello World in Julia

- [Hello World in Julia](#hello-world-in-julia)
- [Introduction](##introduction)
  - [Operations](###operations)
  - [Strings](###strings)
  - [Assignment](###assignment)
  - [Comparison and Logical Operators](#comparison-and-logical-operators)
  - [More on `prinln()`](#more-on-println)
- [Programming Structure](#programming-sturcutree)
  - [Annotations](#annotations)
  - [Combined Expressions](#combined-expressions)
  - [Conditionals](#conditionals)
  - [Loops](#loops)
  - [Defining Functions](#defining-functions)
- [Data Structures in Julia](#data-structures-in-julia)

## Introduction

In [ ]:
println("Hello World!")

In [ ]:
name = "Richard"
println("Hello $(name)!")

In [ ]:
println("1 + 1 = $(1 + 1)")

In [ ]:
😄 = "smile"
ϵ = 2.793e-5

println("$(😄) = $(ϵ)")

In [ ]:
π

### Operations

In [ ]:
println(typeof(π))
println(typeof(1.234))
println(typeof(1))
println(typeof("Hello World!"))

In [ ]:
(1.3 + 2.5)*2.0 - 3.6/1.2 + 1.2^2

In [ ]:
10 + 2*3 - 3*4

In [ ]:
10/2 # always return Float64

In [ ]:
5 ÷ 2 # integer division

In [ ]:
10 % 3

In [ ]:
divrem(10, 3)

In [ ]:
"""
other operations: 
    log, exp, sqrt, sin cos, tan
    round(Int, x), round(x, digits=2), round(x)
    floor(Int, x), floor(x), ceil(Int, x), ceil(x)
    factorial(n), binomial(n, k)
    gcd(x, y), lcm(x, y)
    ndigits()
    evalpoly
"""

### Strings

In [ ]:
"--+" ^ 3 # string repetition

In [ ]:
string(:name)
Symbol("name")

In [3]:
@enum Fruit apple pear orange

my_order = orange
## orange::Fruit = 2

println(typeof(my_order))
println(Integer(my_order))

Fruit
2


### Assignment

In [5]:
x = 123
y = 1+3/2

x + y*2

128.0

In [6]:
x + 2y

128.0

In [7]:
x = y = z = 1

1

In [8]:
x = 123
x += 100

223

In [ ]:
"""
Compare: y = x, y = copy(x), y = deepcopy(x)
"""

### Comparison and Logical Operators

In [11]:
1 == 1.0        ## true
2 != 2.0001     ## true
3.5 > -1        ## true
3.5 < -1.5      ## false
3.5 >= 3.5      ## true
3.5 <= 3.5      ## true

true

In [12]:
"abc" == "ABC"  ## false
"ab" < "abc"    ## true

true

In [13]:
age = 35; sex = "F"

println(age < 18)
println(sex == "F")

age < 18 && sex == "F"  ## false
age >= 18 || sex == "M" ## true

false
true


### More on `println()`

In [14]:
x = 123
y = 1+3/2

println(x + 2y)

128.0


In [16]:
println("x = ", x, ", y = ", y, ", x+2y = ", x+2y)

x = 123, y = 2.5, x+2y = 128.0


In [17]:
println("x = $x, y = $y, x+2y = $(x+2y)")

x = 123, y = 2.5, x+2y = 128.0


In [18]:
@show 1+2

1 + 2 = 3


3

In [19]:
display(1+2)

3

## Programming Sturcutre

### Annotations

In [20]:
# this is an annotation
function f(x)
    #=
    This is a comment:
    This function evaluates a polynomial x^2 + 1
    =#
    return x^2 + 1 # return value
end

f (generic function with 1 method)

### Combined Expressions

In [21]:
z = begin
    x = 1
    y = 2
    x + y
end

println(z)

3


In [22]:
z = (x = 1; y = 2; x + y)
println(z)

3


In [23]:
x = 1 + 2; println("x = $x")

x = 3


### Conditionals

In [24]:
#=
The expression cond && expr will evaluate expr only if cond is true.
=#
x = -1.44
x < 0 && println("x is negative, x = $x")

x is negative, x = -1.44


In [25]:
#=
The expression cond || expr will evaluate expr only if cond is false.
=#
x < 0 || (y = sqrt(x))

true

In [26]:
x = 1.44
if x >= 0
    y = sqrt(x)
    println("√$x = $y")
end

√1.44 = 1.2


In [27]:
x = -1.44
if x >= 0
    y = sqrt(x)
    println("√$x = $y")
else
    y = sqrt(-x)
    println("√$x = $y * i")
end

√-1.44 = 1.2 * i


In [28]:
age = 25
if age < 18
    println("not an adult")
elseif age < 60
    println("adult")
else
    println("senior")
end

adult


In [29]:
x = -1.44
y = x >= 0 ? sqrt(x) : sqrt(-x)

1.2

In [30]:
x = -1.44
y = ifelse(x >= 0, sqrt(x), sqrt(-x))

DomainError: DomainError with -1.44:
sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).

### Loops

```julia
for loopvar = a:b
    # do something
end
```

In [31]:
for i = 1:3
    y = i^3
    println("i = $i, i^3 = $y")
end

i = 1, i^3 = 1
i = 2, i^3 = 8
i = 3, i^3 = 27


In [32]:
n = 5; p = 1
for i = 1:n
    global p
    p *= i
end
print(p)

120

In [36]:
for i = 1:9
    for j = 1:i
        print("$i×$j=$(i*j) ")
    end
    println()
end

1×1=1 
2×1=2 2×2=4 
3×1=3 3×2=6 3×3=9 


4×1=4 4×2=8 4×3=12 4×4=16 
5×1=5 5×2=10 5×3=15 5×4=20 5×5=25 
6×1=6 6×2=12 6×3=18 6×4=24 6×5=30 6×6=36 
7×1=7 7×2=14 7×3=21 7×4=28 7×5=35 7×6=42 7×7=49 
8×1=8 8×2=16 8×3=24 8×4=32 8×5=40 8×6=48 8×7=56 8×8=64 
9×1=9 9×2=18 9×3=27 9×4=36 9×5=45 9×6=54 9×7=63 9×8=72 9×9=81 


In [37]:
for i = 1:9, j = 1:i
    print("$i×$j=$(i*j) ")
    j == i && println()
end

1×1=1 
2×1=2 2×2=4 
3×1=3 3×2=6 3×3=9 
4×1=4 4×2=8 4×3=12 4×4=16 
5×1=5 5×2=10 5×3=15 5×4=20 5×5=25 
6×1=6 6×2=12 6×3=18 6×4=24 6×5=30 6×6=36 
7×1=7 7×2=14 7×3=21 7×4=28 7×5=35 7×6=42 7×7=49 
8×1=8 8×2=16 8×3=24 8×4=32 8×5=40 8×6=48 8×7=56 8×8=64 
9×1=9 9×2=18 9×3=27 9×4=36 9×5=45 9×6=54 9×7=63 9×8=72 9×9=81 


In [38]:
s = 1; i = 0
while i < 5
    global i, s
    i += 1
    s *= i
end
println(s)

120


***Example***: 


Find the greatest common divisor of two numbers:

$$
210 \mod 24 = 18 \\
24 \mod 18 = 6 \\
18 \mod 6 = 0
$$

Then, the gcd is 6.

In [44]:
function mygcd(m::Int, n::Int)
    local r
    while n ≠ 0
        r = m % n
        m, n = n, r
    end
    return m
end

println(mygcd(210, 24))

6


***Example:***

Find the square root of a number is equivalent to find the root of the following equation:

$$
f(u)=u^2-x=0
$$

With the Newton's method, we can find the root of the equation:

$$
u_n = u_{n-1} - \dfrac{f(u_{n-1})}{f'(u_{n-1})} = u_{n-1}=\dfrac{u_{n-1}^2-x}{2u_{n-1}}=\dfrac{1}{2}\left(u_{n-1}+\dfrac{x}{u_{n-1}}\right)
$$

Given an initial value $u_0$, we repeat the above process until $\left|u_n-u_{n-1}\right|\leq\epsilon$, where $\epsilon$ is a small number such as $10^{-6}$.

In [49]:
function mysqrt(x::Real, eps::Float64=1E-6)
    u = 1.0
    u1 = 0.0
    while abs(u - u1) >= eps
        u1 = u
        u = 0.5 * (u + x/u)
    end
    return u
end

println(mysqrt(2))

1.414213562373095


***Example:***

Mathematician Srinivasa Ramanujan found an infinite series that can be used to generate a numerical approximation of $1/\pi$:

$$
\dfrac{1}{\pi}= \dfrac{2\sqrt{2}}{9801}\sum_{k=0}^{\infty}\dfrac{(4k)!(1103+26390k)}{(k!)^4 396^{4k}}
$$

In [51]:
k = 0; x = 2*sqrt(2)/9801; y = 1103
z = x*y
s = z
while z > 1E-15
    k += 1
    k4 = 4*k
    x *= k4*(k4-1)*(k4-2)*(k4-3)/k^4/396^4
    y += 26390
    z = x*y
    s += z
end

println("k = $k, estimate = $s")
println("Error = s - 1/π = $(s - 1/π)")

k = 2, estimate = 0.3183098861837907
Error = s - 1/π = 0.0


```julia
while true
    # do something
    cond && break
end
```

***Example:***

To estimate the value of $\log(1+x)$, we can use Tyalor's series:

$$
\log(1+x)=x+\sum_{k=2}^\infty(-1)^{k-1}\dfrac{x^k}{k}
$$

In practice, we cannot evaluate the infinite series. Instead, we will set some level of precision such as `eps = 0.0001`.

In [1]:
eps = 0.0001; x = 1.0
y = x; xk = x; sgn = 1; k =1

while true
    global k, sgn, xk, y, eps
    k += 1; sgn *= -1; xk *= x
    item = xk / k
    y += sgn*item
    item < eps && break
end

println("esp = $eps, log(1+$x) = $y, Iterations = $k")

esp = 0.0001, log(1+1.0) = 0.6931971730609582, Iterations = 10001


In [3]:
for i = 1:5
    println(i)
    if i == 3
        continue
    end
    y = i*i
    println(y)
end

1
1
2
4
3
4
16
5
25


### Defining Functions

In [4]:
f(x) = x^2 + 3x + 1

f (generic function with 1 method)

In [5]:
f(2)    ## 11
f(1.1)

5.510000000000001

In [ ]:
function mysum(A)
    s = 0.0     # s = zero(eltype(A))
    for a in A
        s += a
    end
    s
end

***Example:***

Write a function to calculate the standard deviation of a sample:

$$
s = \sqrt{\dfrac{1}{n-1}\sum_{i=1}^n(x_i-x)^2}
$$

In [6]:
# mysd: Input numeric vector x, output its sample standard deivation
function mysd(x)
    n = length(x)
    mx = sum(x) / n
    s = 0.0
    for z in x
        s += (z - mx)^2
    end
    sqrt(s/(n-1))
end

mysd (generic function with 1 method)

In [7]:
mysd([1, 2, 3, 4, 5])

1.5811388300841898

In [10]:
# vectorization
function vectorization(x)
    n = length(x)
    mx = sum(x)/n
    sqrt( sum(x .- mx) / (n-1) )
  end

vectorization (generic function with 1 method)

In [12]:
mysd_vectorization([1, 2, 3, 4, 5])
# vectorization is not necessarily faster than loop,
# especially in the case of Julia

0.0

In [13]:
f_quad(x, a=1, b=0, c=0) = a*x^2 + b*x + c

f_quad (generic function with 4 methods)

In [16]:
function f_quad2(x, a=1, b=0, c=0, descending=true)
    if descending
        return a*x^2 + b*x + c
    else
        return cx^2 + b*x + a
    end
end

f_quad2 (generic function with 5 methods)

In [18]:
function summ(x)
    xm = sum(x) / length(x)
    xs = sum(x .^2) / length(x)
    return xm, xs
end

res1, res2 = summ([1,2,3,4,5])
println("($res1, $res2)")

(3.0, 11.0)


## Data Structures in Julia

### Vectors

In [1]:
v1 = [2, 3, 5, 7, 11, 13, 17]

7-element Vector{Int64}:
  2
  3
  5
  7
 11
 13
 17

In [2]:
v2 = [1.5, 3, 4, 9.12]

4-element Vector{Float64}:
 1.5
 3.0
 4.0
 9.12

In [3]:
v3 = ["apple", "orange", "banana"]
v4 = [123, 3.14, "math", [1, 2, 3]]

4-element Vector{Any}:
 123
   3.14
    "math"
    [1, 2, 3]

In [4]:
length(v1)

7

In [5]:
1:5
1:2:7
5:-1:1

5:-1:1

In [6]:
# To convert a range to a vector, use collect
collect(5:-1:1)

5-element Vector{Int64}:
 5
 4
 3
 2
 1

In [7]:
## Julia starts its indenxing at 1
v1[2]

3

In [8]:
v1[end]

17

In [10]:
# Directly modify the element of a vector
v1[2] = 0
@show v1;

v1 = [2, 0, 5, 7, 11, 13, 17]


In [11]:
v1[2:4]

3-element Vector{Int64}:
 0
 5
 7

In [12]:
v1[2:end]

6-element Vector{Int64}:
  0
  5
  7
 11
 13
 17

In [13]:
v1[2:(end-3)]

3-element Vector{Int64}:
 0
 5
 7

In [14]:
v1[1:2:7]

4-element Vector{Int64}:
  2
  5
 11
 17

In [15]:
v1[end:-1:1]
# is equivalent to
reverse(v1)

7-element Vector{Int64}:
 17
 13
 11
  7
  5
  0
  2

In [16]:
v2[:] .= 0;
@show v2;

v2 = [0.0, 0.0, 0.0, 0.0]


In [17]:
v2 = collect(1:2:17)
v2[1:3] .= 0;
@show v2;

v2 = [0, 0, 0, 7, 9, 11, 13, 15, 17]


In [18]:
v2[1:3] = [101, 303, 505];
@show v2;

v2 = [101, 303, 505, 7, 9, 11, 13, 15, 17]


In [19]:
eltype(v2)

Int64

In [21]:
zeros(3)
zeros(Int64, 3)

3-element Vector{Int64}:
 0
 0
 0

In [23]:
Vector{Float64}(undef, 3)

3-element Vector{Float64}:
 0.0
 0.0
 1.0e-323

In [25]:
y1 = Vector{Int}(undef, 3);
@show y1;
fill!(y1, 100);
@show y1;

y1 = [1, 1, 4493757664]
y1 = [100, 100, 100]


### Stored by Reference

In [26]:
x1 = [1, 2, 3]
x2 = x1
x2[2] = 100
@show x1;

x1 = [1, 100, 3]


In [27]:
x2 === x1

true

In [28]:
# to make a hard copy
x1 = [1, 2, 3]
x2 = copy(x1)
x2[2] = -100
@show x1;
@show x2 === x1;

x1 = [1, 2, 3]
x2 === x1 = false


In [29]:
x1 = [1, 2, 3]
x2 = x1[:]
x2[2] = -100
@show x1;

x1 = [1, 2, 3]


In [30]:
x0 = [3, 4]
x1 = [1, 2, x0]
x1[3][1] = 333
@show x0;

x0 = [333, 4]


In [31]:
# copy() is a shallow copy
x0 = [3, 4]
x1 = [1, 2, x0]
x2 = copy(x1)
x2[1] = 111
x2[3][1] = 333
@show x2;
@show x1;
@show x0;

x2 = Any[111, 2, [333, 4]]
x1 = Any[1, 2, [333, 4]]
x0 = [333, 4]


In [32]:
# usually, we use deepcopy() to solve this problem
x0 = [3, 4]
x1 = [1, 2, x0]
x2 = deepcopy(x1)
x2[1] = 111
x2[3][1] = 333
@show x2;
@show x1;
@show x0;

x2 = Any[111, 2, [333, 4]]
x1 = Any[1, 2, [3, 4]]
x0 = [3, 4]


### Functions on Vectors

In [34]:
# to test if an element is in a vector, we use the in operator
1 in [1, 2, 3]

true

In [33]:
# indexin(a, b) returns the index of each element of a in b (at their first occurrence)
# if an element of a is not in b, the corresponding index is nothing
indexin([1, 3, 5, 3], [1, 2, 3])

4-element Vector{Union{Nothing, Int64}}:
 1
 3
  nothing
 3

In [37]:
# push!(v, x): add x to the end of v
# pushfirst!(v, x): add x to the beginning of v
# insert!(v, k, xi): insert xi at the k-th position of v

v3 = [2, 3, 5]
push!(v3, 7)
@show v3;

pushfirst!(v3, 1)
@show v3;

v3 = [2, 3, 5, 7]
v3 = [1, 2, 3, 5, 7]


In [38]:
# append!(v, u): append u to v
v3 = [2, 3, 5]
append!(v3, [7, 11])
@show v3;

v3 = [2, 3, 5, 7, 11]


In [ ]:
# pop!(v): return the last element of v and remove it from v
# popfirst!(v)
# splice!(v, k): remove the k-th element of v
# empty!(x): remove all elements of x

In [39]:
# replace!(): replace the elements of a vector

x = [1, 2, 1, 4, 1]
replace!(x, 1 => 0)
@show x;

x = [0, 2, 0, 4, 0]


In [40]:
x = [1, 2, 1, 4, 1]
replace!(x, 1 => 0, 4 => 3)
@show x;

x = [0, 2, 0, 3, 0]


In [41]:
x = [1, 2, 1, 4, 1]
replace!(x, 1 => 0, 4 => 3, count = 2)
@show x;

x = [0, 2, 0, 4, 1]


In [42]:
# vcat(): concatenate vectors vertically

v1 = [1, 2]; v2 = [-2, 1]
v3 = vcat(v1, v2)
@show v3;
v3[1] = 111;
@show v1;

v3 = [1, 2, -2, 1]
v1 = [1, 2]


In [44]:
# filter!(f, x): remove the elements of x that do not satisfy f
x = [2, 3, 5, 7, 11, 13]
filter!(a -> a % 3 == 1, x)
show(x)

[7, 13]

In [45]:
# unique(v): remove the duplicated elements of v
# unique!(v): remove the duplicated elements of v (with modification of v)
# sort(v): sort the elements of v
# sort!(v): sort the elements of v (with modification of v)
# sortperm(v): return the permutation of v that sorts v
# maximum(v)
# minimum(v)
# argmax(v): return the index of the maximum element of v
# argmin(v): return the index of the minimum element of v
# findmax(v): return the maximum element and its index of v
# findmin(v): return the minimum element and its index of v
# sum(v): return the sum of the elements of v
# prod(v): return the product of the elements of v
# all(v): return true if all elements of v are true
# any(v): return true if any element of v is true
# x == y: return true if x and y are equal

In [47]:
A = rand(10^7)
sum(A)

5.00053872274413e6

### Broadcasting

In [48]:
sqrt.([1, 2, 3])

3-element Vector{Float64}:
 1.0
 1.4142135623730951
 1.7320508075688772

In [49]:
sin.(A)

10000000-element Vector{Float64}:
 0.5847799575000322
 0.7650489784752608
 0.4042215528181087
 0.6842523125039824
 0.11816506705686577
 0.6790223060904469
 0.35056273341919114
 0.5006947052019792
 0.3341273080216024
 0.7692388188380528
 ⋮
 0.005487331139294377
 0.7629337634185556
 0.7475310036875435
 0.09839706927523575
 0.6857507960793201
 0.5439201833684921
 0.748838177873198
 0.7622490230490543
 0.6957685832424391

### Tuples

In [50]:
(1, 2, 3)
(1, "John", 5.1)

(1, "John", 5.1)

In [51]:
# Single element tuple
(1,)

(1,)

In [54]:
x = ('a', 'b', 'c', 'd')
@show typeof(x);

typeof(x) = NTuple{4, Char}


In [55]:
x[1]

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [56]:
x[2:3]

('b', 'c')

In [57]:
# Illegal!: x[2] = 'x'

In [58]:
(1, 3, 5) < (1, 3, 6)

true

In [59]:
a, b = 13, 17
println("a=$a, b=$b")
a, b = b, a # exchange a and b
println("a=$a, b=$b")

a=13, b=17
a=17, b=13


In [60]:
a, b = [19, 23]
println("a=$a, b=$b")
c, d = (29, 31)
println("c=$c, d=$d")

a=19, b=23
c=29, d=31


In [62]:
# convert tuples to vectors
collect((1, 2, 3))

3-element Vector{Int64}:
 1
 2
 3

In [64]:
# pair two vectors: zip()
x = ["a", "b", "c"]
y = [3, 1, 2]
collect(zip(x, y))

3-element Vector{Tuple{String, Int64}}:
 ("a", 3)
 ("b", 1)
 ("c", 2)

In [107]:
info = (name="Roger", age="0", wechat="xx")

(name = "Roger", age = "0", wechat = "xx")

In [108]:
println(info.name)
println(info.age)
println(info.wechat)

Roger
0
xx


### Named Tuples

In [67]:
tn1 = (; name="John", age=32)
@show tn1[:name];
@show tn1[1];

tn1[:name] = "John"
tn1[1] = "John"


In [69]:
@show tn1.name;

tn1.name = "John"


### Dictionaries

In [70]:
d = Dict("name" => "Li Ming", "age" => 18)

Dict{String, Any} with 2 entries:
  "name" => "Li Ming"
  "age"  => 18

In [71]:
d2orig = [('a', 1), ('b', 2), ('c', 3), ('d', 4)]
d2 = Dict(d2orig)

Dict{Char, Int64} with 4 entries:
  'a' => 1
  'c' => 3
  'd' => 4
  'b' => 2

In [72]:
x = ['a', 'b', 'c', 'd']
y = [1, 2, 3, 4]
d2 = Dict(zip(x, y))

Dict{Char, Int64} with 4 entries:
  'a' => 1
  'c' => 3
  'd' => 4
  'b' => 2

In [73]:
length(d2)

4

In [74]:
Dict{String, Int64}("apple" => 1, "pear" => 2, "orange" => 3)

Dict{String, Int64} with 3 entries:
  "pear"   => 2
  "orange" => 3
  "apple"  => 1

In [75]:
x = "apple" => 1
typeof(x)

Pair{String, Int64}

In [76]:
@show (first(x), last(x));

(first(x), last(x)) = ("apple", 1)


In [77]:
collect(d2)

4-element Vector{Pair{Char, Int64}}:
 'a' => 1
 'c' => 3
 'd' => 4
 'b' => 2

In [78]:
d = Dict("name" => "Li Ming", "age" => 18)
d["age"]

18

In [79]:
get(d, "age", 0)

18

In [80]:
haskey(d, "gender")

false

In [81]:
d["gender"] = "Male";
@show d;

d = Dict{String, Any}("name" => "Li Ming", "gender" => "Male", "age" => 18)


In [ ]:
# delete!(d, key): delete the key-value pair of key in d
# get!(d, key, default): return the value of key in d, if key is not in d, add key to d with value default
# pop!(d, key): return the value of key in d and delete the key-value pair of key in d
# merge(dict1, dict2): merge dict2 into dict1

In [83]:
d2 = Dict('a' => 1, 'b' => 2, 'c' => 3, 'd' => 4)
for k in keys(d2)
    println("$k => $(d2[k])")
end

a => 1
c => 3
d => 4
b => 2


In [84]:
@show 'a' in keys(d2);
@show 'g' ∈ keys(d2);

'a' in keys(d2) = true
'g' ∈ keys(d2) = false


In [85]:
for k in sort(collect(keys(d2)))
    println("$k => $(d2[k])")
end

a => 1
b => 2
c => 3
d => 4


In [87]:
d2p = collect(d2)
sort!(d2p, by=first)
for (k, v) in d2p
    println("$k ==> $v")
end

a ==> 1
b ==> 2
c ==> 3
d ==> 4


In [88]:
collect(values(d2))

4-element Vector{Int64}:
 1
 3
 4
 2

In [89]:
for (k, v) in d2
    println("$k => $v")
end

a => 1
c => 3
d => 4
b => 2


In [90]:
[(k, v) for (k, v) in d2]

4-element Vector{Tuple{Char, Int64}}:
 ('a', 1)
 ('c', 3)
 ('d', 4)
 ('b', 2)

In [91]:
Dict(x => x*x for x in [2, 3, 5, 7])

Dict{Int64, Int64} with 4 entries:
  5 => 25
  7 => 49
  2 => 4
  3 => 9

In [92]:
# Application of Dictionary
sex = ["F", "M", "M", "F", "M"]
freqs = Dict()
for xi in sex
    freqs[xi] = get(freqs, xi, 0) + 1
end
@show freqs;

freqs = Dict{Any, Any}("M" => 3, "F" => 2)


In [93]:
function freqd(x)
    y = Dict()
    for xi in x
        y[xi] = get(y, xi, 0) + 1
    end
    return y
end
freqd(sex)

Dict{Any, Any} with 2 entries:
  "M" => 3
  "F" => 2

In [94]:
using StatsBase
StatsBase.countmap(sex)

Dict{String, Int64} with 2 entries:
  "M" => 3
  "F" => 2

In [95]:
function freq(x)
    y = StatsBase.countmap(x)
    return keys(y), values(y)
end
freq(sex)

(["M", "F"], [3, 2])

In [96]:
d3 = freq("disillusionment")
@show d3;

d3 = (['n', 'd', 'i', 's', 'l', 'u', 'o', 'm', 'e', 't'], [2, 1, 3, 2, 2, 1, 1, 1, 1, 1])


### Set

In [97]:
Set(1:3)

Set{Int64} with 3 elements:
  2
  3
  1

In [98]:
# set has no orders and no duplicated elements
Set([1, 2, 3, 2, 1])

Set{Int64} with 3 elements:
  2
  3
  1

In [99]:
Set("keep")

Set{Char} with 3 elements:
  'k'
  'e'
  'p'

In [100]:
Set(["keep"])

Set{String} with 1 element:
  "keep"

In [103]:
# Illegal: Set(1, 2, 3)

In [ ]:
# union(A, B), A ∪ B
# intersect(A, B), A ∩ B
# setdiff(A, B), A \ B
# symdiff(A, B), (A \ B) ∪ (B \ A)
# issetequal(A, B), A == B
# issubset(A, B), A ⊆ B; ⊈: not subset
# ⊇: superset; ⊉: not superset
# ∈, ∋, ∉, ∌

In [104]:
Set("cat") ⊆ Set("atomic")

true

In [105]:
length(Set("keep")) < length("keep")

true

### Self-defined Data Types

In [109]:
mutable struct Rectangle
    xll::Real
    yll::Real
    width::Real
    height::Real
end

In [111]:
rect1 = Rectangle(0, 0, 2, 1)
@show rect1.width;

rect1.width = 2


In [112]:
function move(rect::Rectangle, offset)
    Rectangle(rect.xll + offset[1], rect.yll + offset[2], rect.width, rect.height)
end

move (generic function with 1 method)

In [113]:
rect2 = move(rect1, (20, 10))

Rectangle(20, 10, 2, 1)

#### Application: Complex Numbers

In [ ]:
1 + 1im

In [ ]:
struct MyComplex
    real::Float64
    imag::Float64
end

# A complex number is an object of tpe MyComplex
a = MyComplex(1.0, 2.0)

In [ ]:
# Refine definitions of * for complex numbers
import Base: *

*(a::MyComplex, b::MyComplex) = MyComplex(a.real * b.real - a.imag * b.imag, a.real * b.imag + a.imag * b.real)

In [ ]:
b = MyComplex(3.0, 4.0)
a * b

In [ ]:
# Refine the show method (toString method in Java)
import Base: show

show(io::IO, ::MIME"text/plain", x::MyComplex) = print(io, "$(x.real) + $(x.imag)im")

In [ ]:
a * b

In [ ]:
# Parameterized types
struct MyComplex2{T <: Real}
    real::T
    imag::T
end

MyComplex2{Float32}(1.0f0, 2.0f0)

In [ ]:
# Define a constructor
struct MyComplex3{T <: Real}
    real::T
    imag::T

    MyComplex3(real::T) where {T <: Real} = new{T}(real, 0)
end

MyComplex3(1.0)

## Methods

### Passing by Sharing

In [115]:
function f(n)
    println("Inside f() before changing, n=$n")
    n = -1
    println("Inside f() after changing, n=$n")
    return
end

function test()
    n = 1
    f(n)
    println("Out of f(), n=$n")
end

test()

Inside f() before changing, n=1
Inside f() after changing, n=-1
Out of f(), n=1


In [116]:
function double!(x)
    for i in eachindex(x)
        x[i] *= 2
    end
end

xx = [1, 2, 3]
double!(xx)
@show xx;

xx = [2, 4, 6]


In [117]:
function double_wrong(x)
    x = 2 .* x
     return x
end

xx = [1, 2, 3]
double_wrong(xx)
@show xx;

xx = [1, 2, 3]


### Unnamed Functions

In [118]:
x -> x^2 + 1

#19 (generic function with 1 method)

In [119]:
function (x)
    x^2 + 1
end

#21 (generic function with 1 method)

In [120]:
make_power(α) = x -> x^α
f2 = make_power(2)
f3 = make_power(3)
[f2(2), f3(2)] |> show

[4, 8]

### Chaining and Composite Functions

In [121]:
# x |> f is equivalent to f(x)
# x |> f |> g is equivalent to g(f(x))

[1:5;] |> (x -> x .^ 2) |> sum

55

In [122]:
# g(f.(x)) is equivalent to x .|> f |> g
[1:5;] .|> (x -> x ^ 2) |> sum

55

In [123]:
funcs = [uppercase, lowercase, first]
fruits = ["apple", "pear", "orange"]
fnew = funcs[1] ∘ funcs[3]
y = map(fnew, fruits);
@show y;

y = ['A', 'P', 'O']


### Functions with Variable Number of Arguments

In [124]:
function f_vara1(x, args...)
    println("x=$x")
    println("Other Variables: $args")
end

f_vara1(11, 1, 2, 3)

x=11
Other Variables: (1, 2, 3)


### Recursion

In [127]:
function myfact(n)
    if (n == 1) || (n == 0)
        return 1
    else
        return n * myfact(n-1)
    end
end

myfact(5)

120

In [128]:
function myfib(n)
    if n <= 0
        return 0
    elseif n == 1 || n == 2
        return 1
    else 
        return myfib(n-1) + myfib(n-2)
    end
end

show([(n, myfib(n)) for n = 0:9])

[(0, 0), (1, 1), (2, 1), (3, 2), (4, 3), (5, 5), (6, 8), (7, 13), (8, 21), (9, 34)]

In [129]:
function myfib2(n)
    local f1, f2, f3

    if n <= 0
        return 0
    elseif n == 1 || n == 2
        return 1
    end

    f1 = 1
    f2 = 1
    for i = 3:n
        f3 = f1 + f2
        f1, f2 = f2, f3
    end
    return f3
end

myfib.(1:10) |> show

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55]

### Closure

In [130]:
function counter_old()
    n = 0
    n = n + 1
    return n
end

println(counter_old(), ", ", counter_old())

1, 1


In [131]:
# convert the function into a closure

function make_counter()
    n = 0
    function counter()
        n += 1
        return n
    end
end

my_counter = make_counter()
@show typeof(my_counter)

println(my_counter(), ", ", my_counter())

typeof(my_counter) = var"#counter#31"
1, 2


In [133]:
# convert myfib into closure

function makefib()
    saved = Dict(0 => 0, 1 => 1)
    function fib(n)
        if n ∉ keys(saved)
            saved[n] = fib(n-1) + fib(n-2)
        end
        return saved[n]
    end
end

myfibnew = makefib()
show(myfibnew.(0:9))

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

### Functional Programming

#### `map()`

In [134]:
map(x -> x^2 + 1, [1, 2, 3])

3-element Vector{Int64}:
  2
  5
 10

In [135]:
function fwins(x)
    if x < 0
        y = 0
    elseif x > 100
        y = 100
    else
        y = x
    end
    return y
end

fwins.([-1, 0, 80, 120]) |> show

[0, 0, 80, 100]

In [136]:
map([-1, 0, 80, 120]) do x
    if x < 0
        y = 0
    elseif x > 100
        y = 100
    else
        y = x
    end
    return y
end

4-element Vector{Int64}:
   0
   0
  80
 100

In [137]:
map((x, y) -> 2*x + y, [1, 2, 3], [10, 20, 30]) |> show

[12, 24, 36]

#### `filter()`

In [138]:
filter(x -> x>0, [-2, 0, 1, 2, 3]) |> show

[1, 2, 3]

#### `reduce()`

In [139]:
reduce(+, 1:3)

6

In [140]:
mat = reshape([1:9;], 3, 3)

reduce(+, mat, dims = 1)

1×3 Matrix{Int64}:
 6  15  24

In [142]:
reduce(+, mat, dims = 2)

3×1 Matrix{Int64}:
 12
 15
 18

In [143]:
mapreduce(x -> x ^ 2, +, [1:3;])

14

#### `accumulate()`

In [144]:
cumsum(1:4) |> show

[1, 3, 6, 10]

In [145]:
accumulate(+, 1:5) |> show

[1, 3, 6, 10, 15]

In [146]:
mat = reshape([1:9;], 3, 3)
accumulate(+, mat, dims=1)

3×3 Matrix{Int64}:
 1   4   7
 3   9  15
 6  15  24

In [147]:
accumulate(+, mat, dims=2)

3×3 Matrix{Int64}:
 1  5  12
 2  7  15
 3  9  18

### Exception Handling

```julia
try
    something
catch
    something
finally
    code that will always execute
end
```

In [148]:
x = [2, -2, "a"]
for xi in x
    try
        y = sqrt(xi)
        println("√$(xi)=$(y)")
    catch ex
        if isa(ex, DomainError)
            println("√$(xi): Domain Error!")
        else
            println("√$(xi): Other Errors!")
        end
    end
end

√2=1.4142135623730951
√-2: Domain Error!
√a: Other Errors!


In [ ]:
abstract type TypeA end

struct TypeB <: TypeA end
struct TypeC <: TypeA end

wooo(a1::TypeA, a2::TypeA) = println("A/A")
wooo(a::TypeA, b::TypeB) = println("A/B")

callme(a1::TypeA, a2::TypeA) = wooo(a1, a2)

b = TypeB(); c = TypeC();
callme(c, b)

In [ ]:
wooo(a1::TypeA, a2::TypeA) = println("A/A")